name: 'CppLintAction'
description: |
  A C/C++ lint Action to improve code quality.
  Default only supports pr event. If you want to use for non-pr event,
  you must sepcify the default-branch option.
author: emmettzhang2020@outlook.com
branding:
  icon: "check-circle"
  color: "red"
inputs:
  log-level:
    description: Set log level for cpp-lint-action
    default: info
  clang-format-version:
    description: Choose which clang-format version you want to use
    required: true
    default: 18
  enable-clang-format:
    description: Enable clang-format check
    type: boolean
    default: true
  clang-tidy-version:
    description: Choose which clang-tidy version you want to use
    required: true
    default: 18
  enable-clang-tidy:
    description: Enable clang-tidy check
    type: boolean
    default: true
  clang-tidy-config-file:
    description: clang tidy config file
    type: string
  clang-tidy-database:
    description: clang tidy command database
    type: string
    default: build
  target:
    description: Default branch which usually useds for non-pr related events
    type: string
    required: true

outputs:
  failed:
    description: All checks total failed number.
    value: ${{ steps.cpp_linter_on_unix.outputs.total_failed }}
  clang-tidy-checks-failed:
    description: An integer of how many file fails on clang tidy check
    value: ${{ steps.cpp_linter_on_unix.outputs.clang_tidy_failed_number }}
  clang-format-checks-failed:
    description: An integer of how many file fails on clang format check
    value: ${{ steps.cpp_linter_on_unix.outputs.clang_format_failed_number }}

runs:
  using: "composite"
  steps:
    - name: Install dependencies on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # release_version=$(cat VERSION | sed '/^$/d' | sed 's/[[:space:]]*$//')
        release_version=0.0.32
        echo "Current path: `pwd`, current version: ${release_version}"
        wget -q "https://github.com/emmett2020/cpp-linter/releases/download/v${release_version}/cpp_linter_${release_version}_ubuntu-24.04_${{ runner.arch }}.tar.gz" -O cpp-lint-action.tar.gz
        tar -xvf cpp-lint-action.tar.gz

        cd cpp-lint-action-dist && ls -lrth && ./install.sh


    - name: Run cpp-lint-action on Linux
      id: cpp_linter_on_linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if [[ "${{ inputs.log-level }}" == "trace" ]]; then
          echo "The git repo details:"
          ls -lrthaR .git
        fi
        /usr/local/bin/cpp-lint-action --log-level="${{ inputs.log-level }}"                          \
                                       --enable-clang-format="${{ inputs.enable-clang-format }}"      \
                                       --clang-format-version="${{ inputs.clang-format-version }}"    \
                                       --enable-clang-tidy="${{ inputs.enable-clang-tidy }}"          \
                                       --clang-tidy-version="${{ inputs.clang-tidy-version }}"        \
                                       --clang-tidy-database="${{ inputs.clang-tidy-database }}"      \
                                       --target="${{ inputs.target }}"                                \
                                       --enable-pull-request-review=true
        exit $?


