/*
 * Copyright (c) 2024 Emmett Zhang
 *
 * Licensed under the Apache License Version 2.0 with LLVM Exceptions
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *   https://llvm.org/LICENSE.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#pragma once
#include <stdexcept>

#include <git2/errors.h>

namespace lint {
  /// Throw exception with the given message if condition is true.
  inline void throw_if(bool condition, const std::string &message) {
    if (condition) {
      throw std::runtime_error{message};
    }
  }

  template <typename Func>
  concept noexcept_str_func = requires(Func &&func) {
    requires noexcept(func());
    { func() } -> std::convertible_to<std::string>;
  };

  /// If given condition is true, throw exception with the message generated by the given func.
  template <noexcept_str_func Func>
  void throw_if(bool condition, Func &&func) {
    if (condition) {
      auto msg = std::forward<Func>(func)();
      throw std::runtime_error{msg};
    }
  }

  /// Throw exception with the given message if condition is false.
  inline void throw_unless(bool condition, const std::string &msg) {
    if (!condition) {
      throw std::runtime_error{msg};
    }
  }

  /// If given condition is false, throw exception with the message generated by the given func.
  template <noexcept_str_func Func>
  void throw_unless(bool condition, Func &&func) {
    if (!condition) {
      auto msg = std::forward<Func>(func)();
      throw std::runtime_error{msg};
    }
  }
} // namespace lint
