name: Build And Test On Ubuntu 24.04
on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: "ubuntu-24.04-${{ matrix.compiler }}-${{ matrix.version }}-${{ matrix.build_type }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Installed by github images
          # Details: https://github.com/actions/runner-images
          - { compiler: "gcc",   version: "14.2.0", build_type: Debug,   cxxflags: "" }
          - { compiler: "gcc",   version: "14.2.0", build_type: Release, cxxflags: "" }
          - { compiler: "clang", version: "18.1.3", build_type: Release, cxxflags: "" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup C/C++ Compiler
        run: |
          if [[ "${{ matrix.version }}" == "x.x.x" ]]; then
            echo "Install a specific compiler version."
          fi

          major=$(echo ${{ matrix.version }} | cut -d'.' -f1)
          if [[ "${{ matrix.compiler }}" == "clang" ]]; then
            echo "CC=clang-${major}" >> ${GITHUB_ENV}
            echo "CXX=clang++-${major}" >> ${GITHUB_ENV}
          else
            echo "CC=gcc-${major}" >> ${GITHUB_ENV}
            echo "CXX=g++-${major}" >> ${GITHUB_ENV}
          fi
          echo "${CC}, ${CXX}"

      - name: Install Dependencies
        run: |
          sudo apt install ninja-build;

      - name: CMake
        run: |
          set -ex;
          cmake -S . -B build -GNinja \
            -DCMAKE_CXX_FLAGS="${{ matrix.cxxflags }}" \
            -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}";

      - name: Compile
        run: |
          cmake --build build -v

      - name: Run Unittests
        run: |
          ./build/tests/test_git;

