name: Release On Ubuntu24.04
on:
  push:
    branches: [master, main]

jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test_on_ubuntu_2404.yml

    
  start-to-package:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Deployment Dependencies
        run: |
          sudo apt install pax-utils

      - name: Pack
        run: |
          sudo ./package.sh



