name: Test Action
on:
  push:
    branches: [master, main]


jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./

