name: Test Action
on:
  workflow_dispatch:
    inputs:
      log-level:
        required: true
        type: choice
        options:
          - TRACE
          - DEBUG
          - INFO
        default: TRACE

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./
        with:
          log-level: ${{ inputs.log-level }}
          clang-tidy-version: 18

