name: Test Action
on:
  push:
    branches: [master, main]

  workflow_dispatch:
    inputs:
      log_level:
        required: true
        type: choice
        options:
          - TRACE
          - DEBUG
          - INFO
        default: TRACE

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./
        with:
          log_level: ${{ inputs.log_level }}

